### ISSUE TITLE
<class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry

### ISSUE THREAD

**Issue by carouselcarousel** [lanjelot/patator#191] opened 2023-02-24 14:03 UTC
Warnign message:
/usr/bin/patator:2601: DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13
  from telnetlib import Telnet
  
  For every entry I get this error:
  <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''")

Using the latest version of patator: "patator is already the newest version (0.9-3)."
using the latest pycurl: "Requirement already satisfied: pycurl in /usr/lib/python3/dist-packages (7.45.2)"

**Comment by LittleAunt** [comment] 2023-03-07 03:38
I have the same problem!!!

**Comment by carouselcarousel** [comment] 2023-03-10 19:03
workaround. use the windows exe.
https://github.com/maaaaz/patator-windows/archive/master.zip

**Comment by lanjelot** [comment] 2023-10-09 05:46
duplicate of #195

**Closed by lanjelot** 2023-10-09 05:46 UTC
